import React from 'react';
import type { Metadata } from 'next';
// import '@tectus/styles/globals.scss';

export const metadata: Metadata = {
  title: 'Tectus GO',
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
