import React from 'react';
import type { Metadata } from "next";
// import '@tectus/styles/globals.scss';
import './main.scss';
import { ThemeProvider } from '@tectus/ui/ThemeProvider';
import { UiSnackbarProvider } from '@tectus/ui';


export const metadata: Metadata = {
  title: "Tectus GO",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body>
        <ThemeProvider>
          <UiSnackbarProvider>
            {children}
          </UiSnackbarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
