import React from 'react';
import type { Metadata } from "next";
import '@tectus/styles/globals.scss';
import './main.scss';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@tectus/ui/ThemeProvider';
import { UiSnackbarProvider } from '@tectus/ui';


const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic']
});

export const metadata: Metadata = {
  title: "Tectus GO",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <ThemeProvider>
          <UiSnackbarProvider>
            {children}
          </UiSnackbarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
